# Testing Configuration for MelodyMaster V1

# Model Settings
model:
  name: "opentunesai/melodymaster-v1"
  generation:
    max_length: 30  # seconds
    temperature: 1.0
    top_k: 250
    top_p: 0.0

# Test Suite Configuration
test_suite:
  num_test_cases: 50
  test_batch_size: 5
  timeout_seconds: 300  # 5 minutes per test batch

# Quality Thresholds
minimum_success_rate: 0.95  # 95% of generations must succeed
quality_metrics:
  min_audio_length: 5  # seconds
  max_audio_length: 30  # seconds
  min_quality_score: 0.7

# Test Categories
test_categories:
  - genre_variety     # Test different music genres
  - style_transfer    # Test style adaptation
  - prompt_handling   # Test different prompt types
  - error_handling    # Test edge cases

# Logging
logging:
  level: "INFO"
  save_test_outputs: true
  output_dir: "test_results"
  save_failures: true  # Save failed generations for analysis
