# Training Configuration for MelodyMaster V1

# Model Configuration
model:
  base_model: "facebook/musicgen-melody"
  output_model: "opentunesai/melodymaster-v1"

# Dataset Configuration
dataset:
  name: "google/musiccaps"
  subset_size: 1000  # Number of samples to use for minimal fine-tuning
  validation_split: 0.1
  max_duration: 10  # seconds

# Training Parameters
training:
  batch_size: 4
  learning_rate: 2e-5
  num_epochs: 10
  gradient_accumulation_steps: 4
  mixed_precision: "fp16"
  save_steps: 500
  eval_steps: 100

# Optimization
optimizer:
  name: "AdamW"
  parameters:
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999

# Hardware
hardware:
  device: "cuda"
  num_workers: 2

# Logging
logging:
  log_level: "INFO"
  save_model_every: 1000
  evaluate_every: 100
