# Validation Configuration for MelodyMaster V1

# Validation Dataset
validation_data:
  size: 100  # Number of validation samples
  frequency: 500  # Validate every N steps

# Validation Metrics
metrics:
  audio_quality:
    min_threshold: 0.7
    target: 0.85
  
  generation_length:
    min_seconds: 5
    max_seconds: 30

  text_alignment:
    min_score: 0.6

# Early Stopping
early_stopping:
  patience: 3
  min_delta: 0.01
  monitor: "audio_quality"

# Logging
logging:
  level: "INFO"
  save_predictions: true
  num_examples: 5  # Number of examples to log
